### PR TITLE
update the sourceMappingURL (now with tests!)

### LINKED ISSUE #62: After rename a sourcemap, sourceMappingURL should be updated with the new map file
Hey all,

After run `filerev` with sourceMaps for JS and CSS, I found with there is none update of the `sourceMappingURL` pointing to the new `.map` file.

Current behavior:
1- a.js with sourceMappingURL=a.js.map
2- run filerev
3- a.12345678.js with sourceMappingURL=a.js.map

Expected behavior:
1- a.js with sourceMappingURL=a.js.map
2- run filerev
3- a.12345678.js with sourceMappingURL=a.12345678.js.map

Is there something complicated behind this issue?

Thanks!

### PR DESCRIPTION
**Pull request by yoshokatana**
updated ncthis's PR #67 to use grunt file api methods, added tests (fixes #62)

### CODE REVIEW

**Comment by jtheoof** [comment]
:+1:

**Comment by charlespina** [comment]
Any news ? Seems like yoshokatana addressed the issues in ncthis's PR. Is there anything outstanding?

**Comment by jtheoof** [comment]
I agree, I do not see what's holding things here.

**Comment by kevva** [comment]
Could you fix merge conflicts?

**Comment by yoshokatana** [comment]
Roger, will do.

**Comment by kevva** [comment]
```
$ git remote add source https://github.com/yeoman/grunt-filerev.git
$ git pull --rebase source master
```

**Comment by yoshokatana** [comment]
I couldn't seem to checkout the specific commit from this PR, so here's an updated one (with an updated test): #79

**Pull request closed without merging**
